# Generated by Django 5.2.7 on 2026-01-17 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_employee_created_at_employee_is_deleted_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_department',
            field=models.CharField(blank=True, choices=[('service', 'Service'), ('deliver', 'Deliver'), ('office', 'Office'), ('mechanic', 'Mechanic')], max_length=20, null=True),
        ),
    ]
