# Generated by Django 5.2.7 on 2026-06-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
