# Generated by Django 5.2.6 on 2026-06-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='break_duration',
            field=models.IntegerField(default=0, help_text='Break duration in minutes'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('rotational', 'Rotational'), ('flexible', 'Flexible')], default='fixed', max_length=20),
        ),
    ]
