# Generated by Django 5.2.7 on 2025-12-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('issue_category', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_issue_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('media_file', models.FileField(blank=True, max_length=500, null=True, upload_to='reports/media/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Issue',
                'verbose_name_plural': 'Report Issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
