# Generated by Django 5.2.8 on 2026-02-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_reportissue_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryVehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temporary_vehicles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_images', to='profileapp.vehicleassignment')),
            ],
        ),
    ]
