# Generated by Django 5.2.8 on 2026-02-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_temporaryvehicleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleassignment',
            name='temporary_vehicle_image',
        ),
    ]
