# Generated by Django 5.2.8 on 2026-02-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_remove_vehicleassignment_temporary_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportissue',
            name='media_file',
        ),
        migrations.CreateModel(
            name='ReportIssueMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='reports/media/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='profileapp.reportissue')),
            ],
            options={
                'verbose_name': 'Report Issue Media',
                'verbose_name_plural': 'Report Issue Media',
            },
        ),
    ]
