# Generated by Django 5.2.8 on 2026-02-26 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_remove_reportissue_media_file_reportissuemedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image',
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profileapp.vehicle')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
