# Generated by Django 5.2.8 on 2026-02-26 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_remove_vehicle_vehicle_image_vehicleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleissue',
            name='vehicle_issue_image',
        ),
        migrations.CreateModel(
            name='VehicleIssueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_issue/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profileapp.vehicleissue')),
            ],
        ),
    ]
