# Generated by Django 5.2.7 on 2026-07-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='avatar_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
