# Generated by Django 5.2.7 on 2026-07-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_systemuser_avatar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
