# Generated by Django 5.2.7 on 2026-07-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_systemuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
