# Generated by Django 5.2.7 on 2025-12-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_servicetaskdax_vehicle_make_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytask',
            name='invoice_numbers',
        ),
        migrations.RemoveField(
            model_name='task',
            name='address',
        ),
        migrations.RemoveField(
            model_name='task',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_nothing_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='location',
        ),
        migrations.RemoveField(
            model_name='task',
            name='percentage_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_assign_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_completed_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_notes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_start_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='task',
            name='vehicle_details',
        ),
        migrations.RemoveField(
            model_name='task',
            name='vehicle_image_after',
        ),
        migrations.RemoveField(
            model_name='task',
            name='vehicle_image_before',
        ),
        migrations.RemoveField(
            model_name='task',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='task',
            name='vehicle_year',
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='DeliveryId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='task_assign_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='task_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='task_completed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='task_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='delivery_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='icon_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('office', 'Office'), ('service', 'Service'), ('mechanic', 'Mechanic')], default='nothing', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('delivery', 'Delivery'), ('office', 'Office'), ('service', 'Service/Detailing')], max_length=20),
        ),
    ]
