# Generated by Django 5.2.7 on 2025-12-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_deliverytask_invoice_numbers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverytask',
            old_name='task_assign_time',
            new_name='task_assign_datetime',
        ),
        migrations.RenameField(
            model_name='deliverytask',
            old_name='task_start_time',
            new_name='task_start_datetime',
        ),
    ]
