# Generated by Django 5.2.7 on 2025-12-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_task_assign_time_deliverytask_task_assign_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_progress_images/'),
        ),
    ]
