# Generated by Django 5.2.7 on 2025-12-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_deliverytask_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bay_number', models.CharField(blank=True, max_length=255, null=True)),
                ('Machine_type', models.CharField(blank=True, choices=[('hp_machine', 'Hp Machine'), ('steam_machine', 'Steam Machine')], max_length=255, null=True)),
                ('Machine_serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('spare_part_details', models.TextField(blank=True, null=True)),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_details', to='task.task')),
            ],
        ),
    ]
