# Generated by Django 5.2.7 on 2025-12-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='Machine_serial_number',
            field=models.CharField(blank=True, choices=[('SN001', 'SN001 - HP Machine Model X'), ('SN002', 'SN002 - HP Machine Model Y'), ('SN003', 'SN003 - Steam Machine Model A'), ('SN004', 'SN004 - Steam Machine Model B'), ('SN005', 'SN005 - HP Machine Model Z')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='bay_number',
            field=models.CharField(blank=True, choices=[('bay_1', 'Bay 1'), ('bay_2', 'Bay 2'), ('bay_3', 'Bay 3'), ('bay_4', 'Bay 4'), ('bay_5', 'Bay 5')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='part_number',
            field=models.CharField(blank=True, choices=[('P001', 'P001 - Gear Assembly'), ('P002', 'P002 - Motor Unit'), ('P003', 'P003 - Control Panel'), ('P004', 'P004 - Pressure Valve'), ('P005', 'P005 - Sensor Module')], max_length=255, null=True),
        ),
    ]
