# Generated by Django 5.2.7 on 2025-12-31 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_mechanic_machine_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailing_site', models.CharField(blank=True, choices=[('7086_autopro', '7086 – Autopro'), ('7025_autopro', '7025 – Autopro'), ('7028_autopro', '7028 – Autopro'), ('7005_autopro', '7005 – Autopro'), ('1096_autopro', '1096 – Autopro')], max_length=255, null=True)),
                ('plu', models.CharField(blank=True, choices=[('1', 'Number 1 (PLU eg.)'), ('2', 'Number 2 (PLU eg.)'), ('3', 'Number 3 (PLU eg.)'), ('4', 'Number 4 (PLU eg.)')], max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('1', 'Category 1 eg.'), ('2', 'Category 2 eg.'), ('3', 'Category 3 eg.'), ('4', 'Category 4 eg.')], max_length=255, null=True)),
                ('sub_service', models.CharField(blank=True, choices=[('1', 'Sub Service 1 eg.'), ('2', 'Sub Service 2 eg.'), ('3', 'Sub Service 3 eg.'), ('4', 'Sub Service 4 eg.')], max_length=255, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advantage_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advantage_details', to='task.task')),
            ],
        ),
    ]
