# Generated by Django 5.2.7 on 2025-12-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_serviceadvantage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskduty',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='officetask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='servicetask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskduty',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskprogressimage',
            name='task',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='coating_layers',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='detailing_site',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='invoice_pri_image',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='other_site_name',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='ppf_custom_text',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='ppf_type',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='shared_staff_details',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='tinting_custom_text',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='tinting_percentage',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='tinting_type',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='work_location',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='completion_image',
            field=models.ImageField(blank=True, null=True, upload_to='mechanic_task_images/'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='completion_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceadvantage',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceadvantage',
            name='completion_image',
            field=models.ImageField(blank=True, null=True, upload_to='advantage_task_images/'),
        ),
        migrations.AddField(
            model_name='serviceadvantage',
            name='completion_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceadvantage',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetaskdax',
            name='invoice_pr_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_pr_images/'),
        ),
        migrations.AddField(
            model_name='servicetaskdax',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_after_images/'),
        ),
        migrations.AlterField(
            model_name='servicetaskdax',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('invoice_received', 'Invoice Received'), ('pr_received', 'PR Received')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ServiceDaxTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailing_site', models.CharField(choices=[('mq_dubai_showroom', 'MQ Dubai Showroom (SZR)'), ('mq_delta_service', 'MQ Delta Service Center'), ('mq_ai_quad_service', 'MQ AI Quad Service Center'), ('mq_shirajah_showroom', 'MQ Shirajah Showroom'), ('mq_abu_dhabi_showroom', 'MQ Abu Dhabi Showroom'), ('mq_abu_dhabi_service', 'MQ Abu Dhabi Service Center'), ('mq_ai_ain_showroom', 'MQ AI Ain Showroom'), ('mq_ai_ain_service', 'MQ AI Ain Service Center'), ('mq_fujianni_showroom', 'MQ Fujianni Showroom'), ('mq_fujianni_service', 'MQ Fujianni Service Center'), ('premier_car_care', 'Premier Car Care (Ellie Motors)'), ('camps_ai_quad', 'Camps (AI Quad)'), ('emperor_garage', 'Emperor Garage'), ('five_star_garage', 'Five Star Garage'), ('golden_palace', 'Golden Palace'), ('pos_automotive', 'POS Automotive'), ('office', 'Office'), ('others', 'Others')], max_length=50)),
                ('other_site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type', models.CharField(choices=[('exterior_detailing', 'Exterior Detailing'), ('interior_detailing', 'Interior Detailing'), ('interior_exterior_detailing', 'Interior & Exterior Detailing'), ('tinting', 'Tinting'), ('ceramic_coating', 'Ceramic Coating'), ('borophene_coating', 'Borophene Coating'), ('graphene_coating', 'Graphene Coating'), ('ppf', 'PPF'), ('others', 'Others')], max_length=50)),
                ('tinting_type', models.CharField(blank=True, choices=[('standard', 'Standard Tinting'), ('premium', 'Premium Tinting')], max_length=20, null=True)),
                ('tinting_percentage', models.CharField(blank=True, choices=[('0', '0%'), ('30', '30%'), ('50', '50%'), ('70', '70%')], max_length=3, null=True)),
                ('coating_layers', models.CharField(blank=True, choices=[('1_layer', '1 Layer'), ('2_layer', '2 Layer'), ('3_layer', '3 Layer')], max_length=10, null=True)),
                ('ppf_type', models.CharField(blank=True, choices=[('ppf_prudence', 'PPF PRUDENCE'), ('ppf_st_quard', 'PPF ST. QUARD'), ('ppf_matte', 'PPF MATTE'), ('ppf_magnifence', 'PPF MAGNIFENCE'), ('ppf_dazzling_silver', 'PPF DAZZLING SILVER')], max_length=30, null=True)),
                ('roll_meter', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dax_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_dax_types', to='task.servicetaskdax')),
            ],
        ),
        migrations.DeleteModel(
            name='Duty',
        ),
        migrations.DeleteModel(
            name='OfficeTask',
        ),
        migrations.DeleteModel(
            name='ServiceTask',
        ),
        migrations.DeleteModel(
            name='TaskDuty',
        ),
        migrations.DeleteModel(
            name='TaskProgressImage',
        ),
    ]
