# Generated by Django 5.2.7 on 2026-01-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_taskduty_duty_remove_officetask_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedaxtypes',
            name='coating_layers',
        ),
        migrations.RemoveField(
            model_name='servicedaxtypes',
            name='ppf_type',
        ),
        migrations.RemoveField(
            model_name='servicedaxtypes',
            name='tinting_percentage',
        ),
        migrations.RemoveField(
            model_name='servicedaxtypes',
            name='tinting_type',
        ),
        migrations.AddField(
            model_name='servicedaxtypes',
            name='layers',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicedaxtypes',
            name='level',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='servicedaxtypes',
            name='service_sub_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicedaxtypes',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
