# Generated by Django 5.2.7 on 2026-01-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_remove_servicedaxtypes_coating_layers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedaxtypes',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
