# Generated by Django 5.2.7 on 2026-01-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_servicedaxtypes_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaskdax',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
