# Generated by Django 5.2.7 on 2026-01-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_servicetaskdax_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaskdax',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetaskdax',
            name='progress_image',
            field=models.ImageField(blank=True, null=True, upload_to='dax_progress_images/'),
        ),
        migrations.AddField(
            model_name='servicetaskdax',
            name='progress_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetaskdax',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DaxServiceDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dax_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='task.servicetaskdax')),
            ],
        ),
    ]
