# Generated by Django 5.2.7 on 2026-01-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_servicetaskdax_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedaxtypes',
            name='detailing_site',
        ),
        migrations.RemoveField(
            model_name='servicedaxtypes',
            name='other_site_name',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='progress_image',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='progress_notes',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='vehicle_model',
        ),
        migrations.AddField(
            model_name='servicetaskdax',
            name='detailing_site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='DaxServiceDuty',
        ),
    ]
