# Generated by Django 5.2.7 on 2026-01-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_remove_servicedaxtypes_detailing_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaskdax',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
