# Generated by Django 5.2.7 on 2026-01-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_servicedaxtypes_completed_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedaxtypes',
            name='completed_percentage',
        ),
        migrations.AddField(
            model_name='servicedaxtypes',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
