# Generated by Django 5.2.7 on 2026-01-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_remove_servicedaxtypes_completed_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaskdax',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetaskdax',
            name='completion_image',
            field=models.ImageField(blank=True, null=True, upload_to='dax_task_images/'),
        ),
        migrations.AddField(
            model_name='servicetaskdax',
            name='completion_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetaskdax',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
