# Generated by Django 5.2.7 on 2026-01-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_servicetaskdax_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
