# Generated by Django 5.2.7 on 2026-01-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_mechanic_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='started_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
