# Generated by Django 5.2.7 on 2026-01-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_alter_mechanic_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceadvantage',
            name='started_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
