# Generated by Django 5.2.7 on 2026-01-22 10:18

import django.db.models.deletion
from django.db import migrations, models



def populate_plu(apps, schema_editor):
    PLU = apps.get_model('task', 'PLU')
    data = [
        {'id': 1, 'plu': 'Number 1 (PLU eg.)', 'category': 'Category 1 eg.', 'sub_service': 'Sub Service 1 eg.'},
        {'id': 2, 'plu': 'Number 2 (PLU eg.)', 'category': 'Category 2 eg.', 'sub_service': 'Sub Service 2 eg.'},
        {'id': 3, 'plu': 'Number 3 (PLU eg.)', 'category': 'Category 3 eg.', 'sub_service': 'Sub Service 3 eg.'},
        {'id': 4, 'plu': 'Number 4 (PLU eg.)', 'category': 'Category 4 eg.', 'sub_service': 'Sub Service 4 eg.'},
    ]
    for item in data:
        PLU.objects.create(**item)
    
    # Reset sequence
    # Note: This is Postgres specific logic mostly, but fairly standard.
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT setval(pg_get_serial_sequence('task_plu', 'id'), 5, false);")

class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_maintenancetaskassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('sub_service', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(populate_plu),
        migrations.RemoveField(
            model_name='serviceadvantage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='serviceadvantage',
            name='sub_service',
        ),
        migrations.AlterField(
            model_name='serviceadvantage',
            name='plu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tasks', to='task.plu'),
        ),
    ]
