# Generated by Django 5.2.7 on 2026-01-22 11:25

import django.db.models.deletion
from django.db import migrations, models


def populate_part_numbers(apps, schema_editor):
    PartNumber = apps.get_model('task', 'PartNumber')
    
    PART_NUMBER_CHOICES = [
        ('P001', 'P001 - Gear Assembly'),
        ('P002', 'P002 - Motor Unit'),
        ('P003', 'P003 - Control Panel'),
        ('P004', 'P004 - Pressure Valve'),
        ('P005', 'P005 - Sensor Module'),
    ]
    
    for code, desc in PART_NUMBER_CHOICES:
        # Extract item name from description if possible
        item_name = desc.split(' - ')[1] if ' - ' in desc else desc
        PartNumber.objects.get_or_create(part_number=code, defaults={'item': item_name})

def migrate_old_data(apps, schema_editor):
    Mechanic = apps.get_model('task', 'Mechanic')
    PartNumber = apps.get_model('task', 'PartNumber')
    
    for mechanic in Mechanic.objects.all():
        if mechanic.old_part_number:
            try:
                part = PartNumber.objects.get(part_number=mechanic.old_part_number)
                mechanic.part_number = part
                mechanic.save()
            except PartNumber.DoesNotExist:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_plu_remove_serviceadvantage_category_and_more'),
    ]

    operations = [
        # 1. Create PartNumber table
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        
        # 2. Populate PartNumber table
        migrations.RunPython(populate_part_numbers),
        
        # 3. Rename existing part_number to old_part_number to save data
        migrations.RenameField(
            model_name='mechanic',
            old_name='part_number',
            new_name='old_part_number',
        ),
        
        # 4. Add new part_number field as ForeignKey
        migrations.AddField(
            model_name='mechanic',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_tasks', to='task.partnumber'),
        ),
        
        # 5. Migrate data from old_part_number to new part_number
        migrations.RunPython(migrate_old_data),
        
        # 6. Remove old fields
        migrations.RemoveField(
            model_name='mechanic',
            name='old_part_number',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='item',
        ),
    ]
