# Generated by Django 5.2.7 on 2026-01-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_partnumber_remove_mechanic_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_maintenance',
        ),
    ]
