# Generated by Django 5.2.7 on 2026-01-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_remove_task_is_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
