# Generated by Django 5.2.7 on 2026-01-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_task_is_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='status_of_delivery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
