# Generated by Django 5.2.8 on 2026-02-25 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0029_alter_mechanic_machine_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='vehicle_image',
        ),
        migrations.CreateModel(
            name='ServiceTaskDaxVehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_after_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dax_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_images', to='task.servicetaskdax')),
            ],
        ),
    ]
