# Generated by Django 5.2.8 on 2026-02-25 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0030_remove_servicetaskdax_vehicle_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTaskDaxInvoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='invoice_pr_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dax_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_images', to='task.servicetaskdax')),
            ],
        ),
    ]
