# Generated by Django 5.2.8 on 2026-02-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0031_servicetaskdaxinvoiceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='invoice_pr_image',
        ),
    ]
