# Generated by Django 5.2.8 on 2026-02-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0032_remove_servicetaskdax_invoice_pr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetaskdax',
            name='completion_image',
        ),
        migrations.CreateModel(
            name='ServiceTaskDaxCompletionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dax_completion_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dax_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_images', to='task.servicetaskdax')),
            ],
        ),
    ]
