# Generated by Django 5.2.8 on 2026-02-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_remove_servicetaskdax_completion_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceTaskDaxVehicleImage',
        ),
    ]
