# Generated by Django 5.2.8 on 2026-02-26 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0034_delete_servicetaskdaxvehicleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceadvantage',
            name='completion_image',
        ),
        migrations.RemoveField(
            model_name='serviceadvantage',
            name='image',
        ),
        migrations.CreateModel(
            name='ServiceAdvantageCompletionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advantage_task_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advantage_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_images', to='task.serviceadvantage')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAdvantageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advantage_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advantage_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='task.serviceadvantage')),
            ],
        ),
    ]
