# Generated by Django 5.2.8 on 2026-03-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0035_remove_serviceadvantage_completion_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytask',
            name='image',
        ),
        migrations.CreateModel(
            name='DeliveryTaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_progress_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='task.deliverytask')),
            ],
        ),
    ]
