# Generated by Django 5.2.8 on 2026-03-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0036_remove_deliverytask_image_deliverytaskimage'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE \"task_serviceadvantage\" ALTER COLUMN \"started_at\" TYPE timestamp with time zone USING (CASE WHEN \"started_at\" IS NOT NULL THEN \"created_at\"::date + \"started_at\" ELSE NULL END)::timestamp with time zone;",
                    reverse_sql="ALTER TABLE \"task_serviceadvantage\" ALTER COLUMN \"started_at\" TYPE time without time zone USING \"started_at\"::time;"
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='serviceadvantage',
                    name='started_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
    ]
