# Generated by Django 5.2.8 on 2026-03-19 05:40

from django.db import migrations, models


def migrate_started_at(apps, schema_editor):
    Mechanic = apps.get_model('task', 'Mechanic')
    from django.utils import timezone
    import datetime
    
    for mech in Mechanic.objects.filter(started_at_old__isnull=False):
        if mech.task and mech.task.created_at:
            base_date = mech.task.created_at.date()
        else:
            base_date = timezone.now().date()
            
        combined_dt = timezone.make_aware(
            datetime.datetime.combine(base_date, mech.started_at_old)
        )
        mech.started_at = combined_dt
        mech.save()

def reverse_migrate_started_at(apps, schema_editor):
    Mechanic = apps.get_model('task', 'Mechanic')
    for mech in Mechanic.objects.filter(started_at__isnull=False):
        mech.started_at_old = mech.started_at.time()
        mech.save()

class Migration(migrations.Migration):

    dependencies = [
        ('task', '0037_alter_serviceadvantage_started_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='started_at',
            new_name='started_at_old',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_started_at, reverse_migrate_started_at),
    ]
