# Generated by Django 5.2.8 on 2026-03-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0038_mechanic_started_at_old_alter_mechanic_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='started_at_old',
        ),
    ]
