# Generated by Django 5.2.7 on 2026-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0039_remove_mechanic_started_at_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='part_items',
            field=models.JSONField(blank=True, default=list, help_text='Array of part items with part_number and item fields'),
        ),
    ]
