# Generated by Django 5.2.7 on 2026-03-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0040_mechanic_part_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='part_items',
            field=models.JSONField(blank=True, default=list, help_text='Array of part items with part_number, item, and quantity fields'),
        ),
    ]
