# Generated by Django 5.2.7 on 2026-03-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0041_remove_mechanic_part_number_remove_mechanic_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='part_items',
        ),
        migrations.CreateModel(
            name='MechanicPartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_items', to='task.mechanic')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_items', to='task.partnumber')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('mechanic', 'part_number')},
            },
        ),
    ]
