# Generated by Django 5.2.6 on 2026-04-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0042_remove_mechanic_part_items_mechanicpartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='employee',
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='task.deliverytask'),
        ),
    ]
