# Generated by Django 5.2.6 on 2026-04-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0043_remove_deliverynote_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='task.deliverytask'),
            preserve_default=False,
        ),
    ]
