# Generated by Django 5.2.7 on 2026-01-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_leave_passport_required_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaktimer',
            name='extend_count',
            field=models.IntegerField(default=0),
        ),
    ]
