# Generated by Django 5.2.7 on 2026-01-19 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_breaktimer_extend_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('break_timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_breaks', to='home.breaktimer')),
            ],
        ),
    ]
