# Generated by Django 5.2.8 on 2026-02-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_extendbreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='signature',
        ),
        migrations.CreateModel(
            name='LeaveAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='leave_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='home.leave')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='signature_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='home.leave')),
            ],
        ),
    ]
