# Generated by Django 5.2.8 on 2026-03-05 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_leave_attachment_remove_leave_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='total_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Total Number of Leave Days'),
        ),
    ]
