# Generated by Django 5.2.7 on 2026-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_branch_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
