# Generated by Django 5.2.7 on 2026-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_avatar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hr/documents/%Y/%m/'),
        ),
    ]
