# Generated by Django 5.2.7 on 2026-07-23 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_empdocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='empdocument',
            name='file_name',
        ),
        migrations.CreateModel(
            name='EmpDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hr/documents/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hr.empdocument')),
            ],
            options={
                'verbose_name': 'Employee Document File',
                'verbose_name_plural': 'Employee Document Files',
                'ordering': ['id'],
            },
        ),
    ]
